openapi: 3.0.3
info:
  title: Notifi-K API
  version: 1.0.0
  description: API base de Notifi-K. Actualmente sin endpoints definidos.

servers:
  - url: http://localhost:8988
    description: Servidor local Laravel

paths: {}
